# ODL Releng build templates
- project:
    name: of-config
    jobs:
        - '{project-name}-clm-{stream}'
        - '{project-name}-distribution-{stream}'
        - '{project-name}-distribution-check-{stream}'
        - '{project-name}-integration-{stream}'
        - '{project-name}-merge-{stream}'
        - '{project-name}-periodic-{stream}'
        - '{project-name}-sonar'
        - '{project-name}-validate-autorelease-{stream}'
        - '{project-name}-verify-{stream}'

    # stream:    release stream (eg. stable-lithium or beryllium)
    # branch:    git branch (eg. stable/lithium or master)
    stream:
        - boron:
            branch: 'master'
            jdk: openjdk8
            jdks:
                - openjdk8
            disable_autorelease: False
            disable_distribution_check: False
        - beryllium:
            branch: 'stable/beryllium'
            jdk: openjdk7
            jdks:
                - openjdk7
                - openjdk8
            disable_autorelease: False
            disable_distribution_check: False

    project: 'of-config'
    project-name: 'of-config'
    mvn-settings: 'of-config-settings'
    mvn-goals: 'clean install -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r '
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'
    archive-artifacts: ''
